language: objective-c
before_install:
  - gem uninstall cocoapods -a
  - gem install cocoapods
  - pod repo update
  - pod install
script:
  - xcodebuild build-for-testing test-without-building -workspace Vulcan.xcworkspace -scheme VulcanTests -configuration Debug -sdk iphonesimulator -destination "name=iPhone 7" ENABLE_TESTABILITY=YES
osx_image: xcode8.1
xcode_workspace: Vulcan.xcworkspace
xcode_scheme: VulcanTests
xcode_sdk: iphonesimulator
